lab5/lab5/lab5/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('register', views.register, name='register'),
                  path('login', views.login_view, name='login'),
                  path('logout', views.logout_view, name='logout'),
                  path('products/', views.products_view, name='products'),
                  path('cart', views.user_cart_view, name='cart'),
                  path('add-to-cart/<int:product_id>', views.add_to_cart, name='add-to-cart'),
                  path('news', views.news_view, name='news'),
                  path('coupons', views.coupons_view, name='coupons'),
                  path('contacts', views.contacts_view, name='contacts'),
                  path('about', views.about_us_view, name='about'),
                  path('glossary', views.glossary_view, name='glossary'),
                  path('customer/orders/<int:order_id>', views.customer_order_details_view,
                       name='customer_order_details'),
                  path('employee/orders/<int:order_id>', views.employee_order_details_view,
                       name='employee_order_details'),
                  path('customer/orders', views.customer_orders_view, name='customer_orders'),
                  path('manage/orders', views.manage_orders_view, name='manage_orders'),
                  path('orders_statistics', views.order_statistics_view, name='orders_statistics'),
                  path('reviews', views.reviews_view, name='reviews'),
                  path('reviews/add', views.add_review_view, name='add_review'),
                  path('cart/remove/<int:cart_item_id>', views.remove_from_cart, name='remove_from_cart'),
                  path('cart/update/<int:cart_item_id>', views.update_cart_item, name='update-cart-item'),
                  path('change_order_status/<int:order_id>', views.change_order_status, name='change_order_status'),
                  path('order_status_distribution', views.order_status_distribution, name='order_status_distribution')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab5/lab5/core/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveSmallIntegerField()

    class Meta:
        permissions = [
            ("customer", "Can perform customers actions"),
        ]


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='employee_images/', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)

    class Meta:
        permissions = [
            ("employee", "Can perform employee actions"),
        ]

    def __str__(self):
        return self.user.username


class ProductCategory(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.OneToOneField(Customer, on_delete=models.CASCADE)


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)


class Order(models.Model):
    class OrderStatus(models.TextChoices):
        Pending = "1", "Pending"
        Accepted = "2", "Accepted"
        Completed = "3", "Completed"

    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    order_status = models.CharField(max_length=10, choices=OrderStatus.choices, default=OrderStatus.Pending)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    product_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)


class Coupon(models.Model):
    code = models.CharField(max_length=20, unique=True)
    discount = models.DecimalField(max_digits=5, decimal_places=2)  # For example, 10.00 for 10%
    expiration_date = models.DateField()

    def __str__(self):
        return self.code


class News(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class GlossaryEntry(models.Model):
    term = models.CharField(max_length=255)
    definition = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.term


class Review(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    review = models.TextField()
    rating = models.PositiveSmallIntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} - {self.rating}/5"

lab5/lab5/templates/orders/customer_order_details.html
{% extends 'base.html' %}
{% block title %}Order Details{% endblock %}
{% block content %}

    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Product Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total Price</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for order_item in order_items %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order_item.product.name }}</td>
                    <td>{{ order_item.product_price }}</td>
                    <td>{{ order_item.quantity }}</td>
                    <td>{{ order_item.total_price }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

{% endblock %}

lab5/lab5/templates/orders/customer_orders.html
{% extends 'base.html' %}
{% block title %}Your Orders{% endblock %}
{% block content %}

    <div class="container">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Created At</th>
                <th scope="col">Status</th>
                <th scope="col">Total Price</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for order in orders %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order.created_at }}</td>
                    <td>{{ order.get_order_status_display }}</td>
                    <td>{{ order.total_price }}</td>
                    <td> <a href="{% url 'customer_order_details' order.id %}">View Details</a></td>
                  </tr>
              {% endfor %}
            </tbody>
        </table>
    </div>
    
{% endblock %}

lab5/lab5/templates/orders/employee_order_details.html
{% extends 'base.html' %}
{% block title %}Order Details{% endblock %}
{% block content %}

    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Product Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total Price</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for order_item in order_items %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order_item.product.name }}</td>
                    <td>{{ order_item.product_price }}</td>
                    <td>{{ order_item.quantity }}</td>
                    <td>{{ order_item.total_price }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <form method="post" action="{% url 'change_order_status' order.id %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="order_status">Select Order Status</label>
                <select multiple class="form-control" id="order_status" name="order_status">
                    {% for value, display in order_statuses %}
                        <option value="{{ value }}" {% if order.order_status == value %}selected{% endif %}>
                            {{ display }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Change Order Status</button>
        </form>

    </div>

{% endblock %}

lab5/lab5/templates/orders/manage_orders.html
{% extends 'base.html' %}
{% block title %}Manage Orders{% endblock %}
{% block content %}

    <div class="container">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Created At</th>
                <th scope="col">Status</th>
                <th scope="col">Total Price</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for order in orders %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order.created_at }}</td>
                    <td>{{ order.get_order_status_display }}</td>
                    <td>{{ order.total_price }}</td>
                    <td> <a href="{% url 'employee_order_details' order.id %}">View Details</a></td>
                  </tr>
              {% endfor %}
            </tbody>
        </table>
    </div>
    
{% endblock %}

lab5/lab5/templates/orders/orders_statistics.html
{% extends 'base.html' %}
{% block title %}Orders Statistics{% endblock %}
{% block content %}

    <div class="container">
        <h1 class="display-4">Total Orders: {{ total_orders }}</h1>
        <h1 class="display-4">Total Revenue: ${{ total_revenue }}</h1>

        <img src="{% url 'order_status_distribution' %}" alt="img">
    </div>

{% endblock %}